export const FETCH_COMPANY_STATE_START =
  "FETCH_COMPANY_STATE_START"
export const FETCH_COMPANY_STATE_SUCCESS =
  "FETCH_COMPANY_STATE_SUCCESS"
export const FETCH_COMPANY_STATE_FAILED =
  "FETCH_DISPUTED_TRANSACTIONS_FAILED"
