//State

export const FETCH_COMPANY_STATE_START =
  "FETCH_COMPANY_STATE_START"
export const FETCH_COMPANY_STATE_SUCCESS =
  "FETCH_COMPANY_STATE_SUCCESS"
export const FETCH_COMPANY_STATE_FAILED =
  "FETCH_COMPANY_STATE_FAILED"

//City

export const FETCH_COMPANY_CITY_START =
  "FETCH_COMPANY_CITY_START"
export const FETCH_COMPANY_CITY_SUCCESS =
  "FETCH_COMPANY_CITY_SUCCESS"
export const FETCH_COMPANY_CITY_FAILED =
  "FETCH_COMPANY_CITY_FAILED"

//State & City

export const FETCH_COMPANY_STATE_CITY_START =
  "FETCH_COMPANY_STATE_CITY_START"
export const FETCH_COMPANY_STATE_CITY_SUCCESS =
  "FETCH_COMPANY_STATE_CITY_SUCCESS"
export const FETCH_COMPANY_STATE_CITY_FAILED =
  "FETCH_COMPANY_STATE_CITY_FAILED"

