export const FETCH_LATEST_TRANS_START = "FETCH_LATEST_TRANS_START"
export const FETCH_LATEST_TRANS_SUCCESS = "FETCH_LATEST_TRANS_SUCCESS"
export const FETCH_LATEST_TRANS_FAILED = "FETCH_LATEST_TRANS_FAILED"
