export const FETCH_LATEST_TRANS_START = "FETCH_LATEST_TRANS_START"
export const FETCH_LATEST_TRANS_SUCCESS = "FETCH_LATEST_TRANS_SUCCESS"
export const FETCH_LATEST_TRANS_FAILED = "FETCH_LATEST_TRANS_FAILED"


export const APPROVE_REJECT_LATEST_TRANSACTION = "APPROVE_REJECT_LATEST_TRANSACTION"
export const APPROVE_REJECT_LATEST_TRANSACTION_SUCCESS = "APPROVE_REJECT_LATEST_TRANSACTION_SUCCESS"
export const APPROVE_REJECT_LATEST_TRANSACTION_FAIL = "APPROVE_REJECT_LATEST_TRANSACTION_FAIL"
