export const FETCH_APPROVED_TRANSACTIONS_START =
  "FETCH_APPROVED_TRANSACTIONS_START"
export const FETCH_APPROVED_TRANSACTIONS_SUCCESS =
  "FETCH_APPROVED_TRANSACTIONS_SUCCESS"
export const FETCH_APPROVED_TRANSACTIONS_FAILED =
  "FETCH_APPROVED_TRANSACTIONS_FAILED"
